
	function _D(e) {
		return {
			method: e.method ?? "GET",
			localURLsOnly: e.localURLsOnly ?? !1,
			unsafeRequest: e.unsafeRequest ?? !1,
			body: e.body ?? null,
			client: e.client ?? null,
			reservedClient: e.reservedClient ?? null,
			replacesClientId: e.replacesClientId ?? "",
			window: e.window ?? "client",
			keepalive: e.keepalive ?? !1,
			serviceWorkers: e.serviceWorkers ?? "all",
			initiator: e.initiator ?? "",
			destination: e.destination ?? "",
			priority: e.priority ?? null,
			origin: e.origin ?? "client",
			policyContainer: e.policyContainer ?? "client",
			referrer: e.referrer ?? "client",
			referrerPolicy: e.referrerPolicy ?? "",
			mode: e.mode ?? "no-cors",
			useCORSPreflightFlag: e.useCORSPreflightFlag ?? !1,
			credentials: e.credentials ?? "same-origin",
			useCredentials: e.useCredentials ?? !1,
			cache: e.cache ?? "default",
			redirect: e.redirect ?? "follow",
			integrity: e.integrity ?? "",
			cryptoGraphicsNonceMetadata: e.cryptoGraphicsNonceMetadata ?? "",
			parserMetadata: e.parserMetadata ?? "",
			reloadNavigation: e.reloadNavigation ?? !1,
			historyNavigation: e.historyNavigation ?? !1,
			userActivation: e.userActivation ?? !1,
			taintedOrigin: e.taintedOrigin ?? !1,
			redirectCount: e.redirectCount ?? 0,
			responseTainting: e.responseTainting ?? "basic",
			preventNoCacheCacheControlHeaderModification: e.preventNoCacheCacheControlHeaderModification ?? !1,
			done: e.done ?? !1,
			timingAllowFailed: e.timingAllowFailed ?? !1,
			urlList: e.urlList,
			url: e.urlList[0],
			headersList: e.headersList ? new ED(e.headersList) : new ED(),
		}
	}