
function Bxe(e, t, r, n, i, s, o, a, l, c, u, f, p) {
	let g = new iM(r)
	return (
		g.registerGroup("", [new aA(n, i, aA.signInCommandID, "$(sign-in) Sign In"), new Hi(), new $F(f, r, t)]),
		g.registerGroup("Completions", [new jF(t, f), new m1(r, f)]),
		g.registerGroup("Code Instruction", [new $y(t, e.extensionUri, s, t.guidelinesWatcher, f)]),
		g.registerGroup("Chat", [
			new Gh(t, r, u, f),
			new iC(t, r, u, f),
			new A1(u),
			new sC(t, r, u, f),
			new oC(t, r, u, f),
			new hF(u, p),
			new aC(t, s, f),
			new p1(e.extensionUri, t, s, r),
		]),
		g.registerGroup("Next Edit Suggestions", [
			new Dc(t, r, f),
			new Tc(t, r, f),
			new uA(t, r, f),
			new dA(t, r, f),
			new Uu(t, r, f),
			new Ou(t, r, f),
			new Xo(t, r, f),
			new Fa(t, r, f),
			new AF(t, r, f),
			new bF(t, r, f),
			new mF(t, r, f),
			new Yh(t, r, f),
			new h_(t, r, f),
			new SF(t, r, f),
			new IF(t, r, f),
			new BF(t, r, f, p),
			new VF(t, r),
			new yF(t, r, f),
			new CF(t, r, f),
			new vF(t, r, f),
			new sf(t, r, f),
			new EF(t, r, f),
			new qu(t, r, f),
			new _F(t, r, f),
			new xF(t, r, f),
			new Co(t, r, f),
			new cC(t, r, f),
		]),
		g.registerGroup("Debug", [
			new KF(t, r),
			new ZF(t, r),
			new pA(t.featureFlagManager),
			new GF(t.featureFlagManager),
		]),
		r.config.remoteAgent.url && g.register([new o1(e.extensionUri, s)]),
		g.registerGroup("", [
			new a1(),
			new l1(),
			new YF(f, r, t),
			new c1(),
			new d1(e.extensionUri, r, s, o, a, l),
			new HF(s),
			new df(t, df.commandIDCommunity),
			new df(t, df.commandIDProfessional),
			new df(t, df.commandIDEnterprise),
			new aA(n, i, aA.signOutCommandID, "$(sign-out) Sign Out"),
			new DF(t, r, f),
		]),
		r.config.autofix.enabled && r.config.autofix.autofixUrl && g.register([new gF(t, s)]),
		g.register([
			new f1(t, e, g),
			new wF(t, r, f),
			new rC(t.featureFlagManager, c),
			new zF(t, s, r),
			new nF(t, e.extensionUri, s),
			new Yy(),
			new Ky(),
			new Jy(),
			new zy(),
			new jy(),
			new Zy(),
			new pC(),
		]),
		g
	)
}