
	var il = require("assert"),
		{ pipeline: _Ge } = require("stream"),
		dr = Xt(),
		{
			RequestContentLengthMismatchError: rq,
			RequestAbortedError: are,
			SocketError: LE,
			InformationalError: nq,
		} = Vr(),
		{
			kUrl: UB,
			kReset: qB,
			kClient: c0,
			kRunning: VB,
			kPending: wGe,
			kQueue: Kf,
			kPendingIdx: iq,
			kRunningIdx: ic,
			kError: oc,
			kSocket: zi,
			kStrictContentLength: IGe,
			kOnError: sq,
			kMaxConcurrentStreams: fre,
			kHTTP2Session: sc,
			kResume: Jf,
			kSize: SGe,
			kHTTPContext: BGe,
		} = Qn(),
		Dd = Symbol("open streams"),
		lre,
		cre = !1,
		OB